apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zero-trust-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        role: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.29
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: zero-trust-demo
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
