apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: mlflow-oidc
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0
          args:
            - start-dev
          ports:
            - containerPort: 8080
          env:
            - name: KC_HTTP_RELATIVE_PATH
              value: /keycloak
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HOSTNAME_URL
              value: http://localhost/keycloak/
            - name: KC_HOSTNAME_ADMIN_URL
              value: http://localhost/keycloak/
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          readinessProbe:
            httpGet:
              path: /keycloak/health/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 1000m
